package com.bedwarsqol.stats;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * The backend optionally baked into the jar at build time as the
 * {@code /cobblify-backend.properties} classpath resource (keys {@code url}, {@code token}),
 * generated by the {@code generateBackendProperties} Gradle task. A blank build carries empty
 * values, so everything here resolves to "" and behavior matches a build with no resource at all.
 * A token without a URL is treated as absent — the baked token may only ever pair with the baked
 * URL (see {@code ClientSettings#backendTarget()}).
 */
public final class BackendDefaults {

    private static final String RESOURCE = "/cobblify-backend.properties";

    private static final BackendTarget BAKED =
            fromStream(BackendDefaults.class.getResourceAsStream(RESOURCE));

    private BackendDefaults() {}

    /** Baked backend base URL, or "" when none was baked in. Never null. */
    public static String url() {
        return BAKED.url;
    }

    /** Baked token, or "" when none was baked in. Never non-empty while {@link #url()} is empty. */
    public static String token() {
        return BAKED.token;
    }

    /**
     * Parses one resource stream ({@code null} = absent resource) and closes it. Package-private
     * for tests: the static init above cannot be swapped per test, this can be fed directly.
     */
    static BackendTarget fromStream(InputStream in) {
        if (in == null) return new BackendTarget("", "");
        Properties p = new Properties();
        try {
            p.load(in);
        } catch (IOException e) {
            return new BackendTarget("", "");
        } finally {
            try { in.close(); } catch (IOException ignored) { }
        }
        String url = p.getProperty("url", "").trim();
        String token = p.getProperty("token", "").trim();
        if (url.isEmpty()) token = ""; // a token without a URL is treated as absent
        return new BackendTarget(url, token);
    }
}
